### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by gmp26** [mme/atom-paredit#3]
[Enter steps to reproduce below:]

While editing https://github.com/gmp26/funnelcljs/edit/master/src/funnel/core.cljs using atomic-chrome 
1. Place cursor between two defn calls e.g. line 16
2. Press Ctrl left-arrow

**Atom Version**: 1.9.6
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-paredit](https://github.com/mme/atom-paredit) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/gmp26/.atom/packages/atom-paredit/node_modules/paredit.js/lib/editor.js:279

TypeError: Cannot read property 'length' of undefined
    at Object.exports.editor.barfSexp (/Users/gmp26/.atom/packages/atom-paredit/node_modules/paredit.js/lib/editor.js:279:45)
    at Object.module.exports.Paredit.barfSexp (/Users/gmp26/.atom/packages/atom-paredit/lib/atom-paredit.coffee:408:32)
    at Object.module.exports.Paredit.barfSexpFwd (/Users/gmp26/.atom/packages/atom-paredit/lib/atom-paredit.coffee:416:6)
    at atom-text-editor.subscriptions.add.atom.commands.add.paredit:barfSexpFwd (/Users/gmp26/.atom/packages/atom-paredit/lib/atom-paredit.coffee:51:89)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -2:21.7.0 paredit:slurpSexpBwd (atom-text-editor.editor.is-focused)
     -2:20.5.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -2:19 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -2:17.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:16.7.0 paredit:barfSexpFwd (atom-text-editor.editor.is-focused)
  2x -2:06.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:04.7.0 paredit:barfSexpFwd (atom-text-editor.editor.is-focused)
  9x -1:55.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:54.2.0 paredit:slurpSexpFwd (atom-text-editor.editor.is-focused)
     -1:52.4.0 paredit:barfSexpFwd (atom-text-editor.editor.is-focused)
     -1:51.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:51.2.0 paredit:slurpSexpFwd (atom-text-editor.editor.is-focused)
     -1:49.9.0 paredit:barfSexpFwd (atom-text-editor.editor.is-focused)
 13x -0:03.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:00.0 paredit:barfSexpFwd (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atom-paredit, v0.2.0 (active)
atomic-chrome, v0.3.0 (active)
git-time-machine, v1.5.3 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.3 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by MartyGentillon** [comment]
[Enter steps to reproduce:]

1. Place cursor on end of line after comment between two defs
2. Press ctrl+left arrow.

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-paredit](https://github.com/mme/atom-paredit) package 0.2.0


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Marty\.atom\packages\atom-paredit\node_modules\paredit.js\lib\editor.js:279

TypeError: Cannot read property 'length' of undefined
    at Object.barfSexp (/packages/atom-paredit/node_modules/paredit.js/lib/editor.js:279:45)
    at Object.barfSexp (/packages/atom-paredit/lib/atom-paredit.coffee:408:32)
    at Object.barfSexpFwd (/packages/atom-paredit/lib/atom-paredit.coffee:416:6)
    at /packages/atom-paredit/lib/atom-paredit.coffee:51:89)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:22.5.0 paredit:openCurly (input.hidden-input)
     -2:22.4.0 paredit:closeCurly (input.hidden-input)
  2x -2:21.5.0 atomic-emacs:forward-char (input.hidden-input)
  2x -2:04.1.0 paredit:newLineAndIndent (input.hidden-input)
  2x -2:03.4.0 atomic-emacs:previous-line (input.hidden-input)
  5x -2:03.0 atomic-emacs:forward-char (input.hidden-input)
     -1:58.8.0 atomic-emacs:backward-char (input.hidden-input)
  3x -1:56.5.0 core:backspace (input.hidden-input)
     -1:54.2.0 paredit:deleteBwd (input.hidden-input)
     -1:52.3.0 core:backspace (input.hidden-input)
 10x -1:49 paredit:deleteBwd (input.hidden-input)
     -1:40 intentions:highlight (input.hidden-input)
  2x -1:39.9.0 paredit:barfSexpFwd (input.hidden-input)
     -1:36.5.0 intentions:highlight (input.hidden-input)
  2x -1:36.3.0 paredit:barfSexpFwd (input.hidden-input)
  4x -1:34.9.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.23 
atom-html-preview 0.1.22 
atom-paredit 0.2.0 
atom-runner 2.7.1 
atom-terminal 0.8.0 
atom-ternjs 0.18.3 
atom-typescript 11.0.3 
atomatigit 1.5.5 
atomic-emacs 0.10.0 
autoclose-html 0.23.0 
build 0.67.0 
build-powershell 0.10.1 
build-tsc 0.7.1 
busy 0.7.0 
busy-signal 1.4.1 
color-picker 2.2.5 
disable-keybindings 0.6.0 
docblockr 0.9.4 
double-tag 0.8.0 
duplicate-line-or-selection 0.9.0 
editor-settings 1.1.2 
emmet 2.4.3 
expand-region 0.2.7 
file-icons 2.1.4 
fonts 2.0.0 
git-log 0.4.1 
git-time-machine 1.5.9 
hex 0.6.2 
highlight-selected 0.13.1 
Hydrogen 1.12.1 
hydrogen-launcher 1.2.1 
indent-guide-improved 1.4.12 
intentions 1.1.2 
key-peek 0.2.12 
language-babel 2.58.0 
language-diff 0.7.0 
language-fish-shell 1.0.5 
language-powershell 4.0.0 
language-tiddlywiki5 0.3.0 
language-unix-shell 0.40.1 
less-than-slash 0.16.0 
linter 2.1.4 
linter-clojure 1.1.3 
linter-eslint 8.1.7 
linter-htmlhint 1.3.3 
linter-stylelint 3.10.0 
linter-tslint 1.3.0 
linter-ui-default 1.2.3 
markdown-preview-plus 2.4.9 
merge-conflicts 1.4.4 
minimap 4.28.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-selection 4.4.0 
open-recent 5.0.0 
package-sync 1.1.0 
Parinfer 1.17.0 
proto-repl 1.4.20 
react 0.16.2 
revert-buffer 0.5.0 
set-syntax 0.3.2 
split-diff 1.3.0 
stacktrace 0.0.2 
Sublime-Style-Column-Selection 1.7.4 
tablr 1.8.3 
todo-show 1.11.0 
url-utils 0.2.1 
```

**Comment by mme** [comment]
Hi, thanks for reporting. Unfortunately I do not have the time to further maintain this project.
