### ISSUE TITLE
Uncaught TypeError: Cannot read property 'createCheckpoint' of undefined

### ISSUE THREAD

**Issue by markaddleman** [mme/atom-paredit#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home Insider Preview
**Thrown From**: [atom-paredit](https://github.com/mme/atom-paredit) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'createCheckpoint' of undefined

```
At C:\Users\markaddleman\.atom\packages\atom-paredit\lib\atom-paredit.coffee:332

TypeError: Cannot read property 'createCheckpoint' of undefined
    at Object.killSexpBwd (/packages/atom-paredit/lib/atom-paredit.coffee:332:19)
    at /packages/atom-paredit/lib/atom-paredit.coffee:46:89)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  3x -1:58.9.0 paredit:closeParens (input.hidden-input)
     -1:56.4.0 core:save (input.hidden-input)
     -1:56 command-palette:toggle (input.hidden-input)
  3x -1:53.7.0 core:move-down (input.hidden-input)
     -1:53 core:confirm (input.hidden-input)
     -1:53 proto-repl:toggle (input.hidden-input)
  2x -1:50.3.0 autocomplete-plus:cancel (atom-text-editor.editor)
     -1:45.8.0 paredit:newLineAndIndent (input.hidden-input)
     -1:45.3.0 paredit:openParens (input.hidden-input)
     -1:43.4.0 editor:delete-to-beginning-of-word (input.hidden-input)
  2x -1:42.5.0 paredit:deleteBwd (input.hidden-input)
     -0:14.8.0 core:save (input.hidden-input)
     -0:12 autocomplete-plus:cancel (atom-text-editor.editor)
     -0:11.2.0 paredit:openParens (input.hidden-input)
     -0:09.3.0 paredit:killSexpBwd (input.hidden-input)
     -0:02.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-paredit 0.2.0 
highlight-selected 0.12.0 
ink 0.6.2 
language-lisp 0.2.0 
lisp-paredit 0.5.5 
Parinfer 1.17.0 
proto-repl 1.4.14 
proto-repl-charts 0.4.0 
proto-repl-sayid 0.1.4 
set-syntax 0.3.2 
tool-bar 1.0.1 
```

**Comment by mme** [comment]
Hi, thanks for reporting. Unfortunately I do not have the time to further maintain this project.
